### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by Xiefengshang** [pcysanji/Clash-Web-Bat#1]
能否增加一个保存该配置上次设置的功能？每次重启之后对应策略组都要重新设置节点感觉很麻烦

**Comment by pcysanji** [comment]
已列入 Todo 了。
不过批处理要实现保存上次的设置，将会是一件很麻烦的事情。不过我会努力尝试的

**Comment by Xiefengshang** [comment]
> 已列入 Todo 了。
> 不过批处理要实现保存上次的设置，将会是一件很麻烦的事情。不过我会努力尝试的

能不能新建一个配置文件来保存上次的配置，下次打开的时候直接读取该文件就可以了

**Comment by pcysanji** [comment]
> > 已列入 Todo 了。
> > 不过批处理要实现保存上次的设置，将会是一件很麻烦的事情。不过我会努力尝试的
> 
> 能不能新建一个配置文件来保存上次的配置，下次打开的时候直接读取该文件就可以了

保存上次的配置文件，和保存配置文件中的设置是不一样的概念。
目前默认是你选择哪个配置文件，下次启动也是默认调用哪个。
但是保存配置文件中的设置，需要调用 clash 的api，来修改配置文件对应的值。不是那么简单能完成的。

**Comment by Xiefengshang** [comment]
> > > 已列入 Todo 了。
> > > 不过批处理要实现保存上次的设置，将会是一件很麻烦的事情。不过我会努力尝试的
> > 
> > 
> > 能不能新建一个配置文件来保存上次的配置，下次打开的时候直接读取该文件就可以了
> 
> 保存上次的配置文件，和保存配置文件中的设置是不一样的概念。
> 目前默认是你选择哪个配置文件，下次启动也是默认调用哪个。
> 但是保存配置文件中的设置，需要调用 clash 的api，来修改配置文件对应的值。不是那么简单能完成的。

好的，祝成功！
