### ISSUE TITLE
问题已经自行解决 感谢

### ISSUE THREAD

**Issue by duzink** [pcysanji/Clash-Web-Bat#3]
问题已经自行解决
感谢

**Comment by Mike-hd123** [comment]
> 问题已经自行解决
> 感谢

怎么解决的求教？？？

**Comment by duzink** [comment]
app目录下新建hide.vbs文件
写入
Set ws = CreateObject("Wscript.Shell") 
   ws.run "cmd /c 你的完整路径\App\startup_agent.bat",vbhide 
之后在启动项里找到之前的clash的启动项然后删除，把新建的hide.vbs设为启动项
重启即可
